version: "3.3"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        volumes:
            - .:/app
            - "/app/node_modules"
        depends_on:
            - mysql_server
        networks:
            - internalnet

    mysql_server:
        image: mysql:8.0
        # command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: a-secret-password
            MYSQL_DATABASE: hy359
            MYSQL_USER: user
            MYSQL_PASSWORD: user
        volumes:
            - ./db:/docker-entrypoint-initdb.d
            - $HOME/mydatabase:/var/lib/mysql
        ports:
            - 9000:3306
        networks:
            - internalnet
        # expose:
        # - 3306
    # volumes:
    #     mysql:
    #     mysql_config:
    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            # - PMA_ARBITRARY=1
            PMA_HOST: mysql_server
            PMA_USER: root
            PMA_PASSWORD: a-secret-password
        hostname: localhost
        depends_on:
            - mysql_server
        networks:
            - internalnet

networks:
    internalnet:
        driver: bridge
